# Generated by Django 4.2.30 on 2026-06-28 15:01

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('excerpt', models.TextField(verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('author_avatar', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Аватар автора')),
                ('date', models.CharField(max_length=100, verbose_name='Дата (текст)')),
                ('image', models.URLField(max_length=1000, verbose_name='Изображение')),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
                ('read_time', models.IntegerField(default=5, verbose_name='Время чтения (мин)')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Статьи блога',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('image', models.URLField(max_length=1000, verbose_name='Изображение')),
                ('tour_count', models.IntegerField(default=0, verbose_name='Кол-во туров')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ForumTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('author_avatar', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Аватар автора')),
                ('date', models.CharField(max_length=100, verbose_name='Дата (текст)')),
                ('replies_count', models.IntegerField(default=0, verbose_name='Кол-во ответов')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплено')),
                ('last_reply', models.CharField(blank=True, max_length=255, null=True, verbose_name='Последний ответ (текст)')),
            ],
            options={
                'verbose_name': 'Тема обсуждения',
                'verbose_name_plural': 'Темы обсуждений',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Подписчик рассылки',
                'verbose_name_plural': 'Подписчики рассылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user_id', models.UUIDField(blank=True, null=True, verbose_name='ID пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('paid', 'Оплачен'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Способ оплаты')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration', models.IntegerField(verbose_name='Длительность (дней)')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Рейтинг')),
                ('reviews_count', models.IntegerField(default=0, verbose_name='Кол-во отзывов')),
                ('image', models.URLField(max_length=1000, verbose_name='Главное изображение')),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='Теги')),
                ('hotel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отель')),
                ('hotel_stars', models.IntegerField(blank=True, null=True, verbose_name='Звёзды отеля')),
                ('included', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Включено')),
                ('not_included', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Не включено')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Горящий тур')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка %')),
                ('max_people', models.IntegerField(default=30, verbose_name='Макс. человек')),
                ('meals', models.TextField(blank=True, null=True, verbose_name='Питание')),
                ('transport', models.TextField(blank=True, null=True, verbose_name='Транспорт')),
                ('guide_language', models.CharField(blank=True, max_length=255, null=True, verbose_name='Язык гида')),
                ('group_size', models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер группы')),
                ('difficulty', models.CharField(blank=True, choices=[('Легкий', 'Легкий'), ('Средний', 'Средний'), ('Сложный', 'Сложный')], max_length=50, null=True, verbose_name='Сложность')),
                ('best_season', models.CharField(blank=True, max_length=255, null=True, verbose_name='Лучший сезон')),
                ('visa_required', models.BooleanField(default=False, verbose_name='Нужна виза')),
                ('insurance_included', models.BooleanField(default=False, verbose_name='Страховка включена')),
                ('free_cancellation', models.BooleanField(default=True, verbose_name='Бесплатная отмена')),
                ('instant_confirmation', models.BooleanField(default=True, verbose_name='Мгновенное подтверждение')),
                ('amenities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Удобства')),
                ('highlights', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Изюминки')),
                ('faqs', models.JSONField(blank=True, default=list, verbose_name='Вопросы и ответы')),
                ('gallery', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=1000), blank=True, default=list, size=None, verbose_name='Галерея')),
                ('departure_cities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Города вылета')),
                ('arrival_info', models.TextField(blank=True, null=True, verbose_name='Информация о прибытии')),
                ('important_notes', models.TextField(blank=True, null=True, verbose_name='Важные заметки')),
                ('suitable_for', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Подходит для')),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Языки')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('avatar', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Всего потрачено')),
                ('orders_count', models.IntegerField(default=0, verbose_name='Кол-во заказов')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('image_url', models.URLField(max_length=1000, verbose_name='URL изображения')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Изображение тура',
                'verbose_name_plural': 'Изображения туров',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('avatar', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Аватар')),
                ('rating', models.IntegerField(verbose_name='Оценка (1-5)')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date', models.CharField(max_length=100, verbose_name='Дата (текст)')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('travel_date', models.DateField(blank=True, null=True, verbose_name='Дата поездки')),
                ('people_count', models.IntegerField(default=1, verbose_name='Кол-во человек')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tours.order', verbose_name='Заказ')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('day_number', models.IntegerField(verbose_name='День')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'День маршрута',
                'verbose_name_plural': 'Маршрут по дням',
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='ForumReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('author_avatar', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Аватар автора')),
                ('content', models.TextField(verbose_name='Сообщение')),
                ('date', models.CharField(max_length=100, verbose_name='Дата (текст)')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tours.forumtopic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Ответ в обсуждении',
                'verbose_name_plural': 'Ответы в обсуждениях',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('activity_type', models.CharField(choices=[('reply', 'Ответ'), ('like', 'Лайк'), ('mention', 'Упоминание')], max_length=20, verbose_name='Тип активности')),
                ('content_preview', models.TextField(blank=True, null=True, verbose_name='Превью содержимого')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tours.forumreply', verbose_name='Ответ')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tours.forumtopic', verbose_name='Тема')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_activities', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Активность в форуме',
                'verbose_name_plural': 'Активность в форумах',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='tours.tour', verbose_name='Тур')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранный тур',
                'verbose_name_plural': 'Избранные туры',
                'unique_together': {('user', 'tour')},
            },
        ),
    ]
